/usr/bin/env python3 ./jobs/finetune_dnabert_autoencoder.py \
    --pretrained-model-artifact 'deep-learning-dna/dnabert-pretrain:v0' \
    --embed-dim 64 \
    --stack 4 \
    --num-heads 4 \
    --pre-layernorm true \
    --batches-per-epoch 100 \
    --val-batches-per-epoch 16 \
    --data-augment true \
    --data-balance false \
    --data-workers 1 \
    --data-artifact 'deep-learning-dna/dnasamples:latest' \
    --epochs 100 \
    --batch-size 512 \
    --optimizer nadam \
    --lr 4e-4
